swagger: '2.0'
info:
  description: API for Issue tracking system
  version: 1.0.0
  title: ITS - API
tags:
  - name: session
    description: API for auth (client)
  - name: profile
    description: API for profile data (client)
  - name: project
    description: API for project data (client)
  - name: issue
    description: API for update media (client)
  - name: media
    description: API for update media (client)
paths:
  /session:
    post:
      tags:
        - session
      summary: Register a new account
      operationId: register
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: 'Email, password and username'
          schema:
            type: object
            required:
              - email
              - password
              - username
            properties:
              email:
                type: string
                format: email
                example: test@gmail.com
              password:
                type: string
                format: hash
                example: 127e6fbfe24a750e72930c220a8e138275656b8e5d8f48a98c3c92df2caba935
              username:
                type: string
                example: ting
      responses:
        '200':
          description: Register success
          schema:
            $ref: '#/definitions/AUTH_RES'
        '400':
          description: Invalid parameter
        '401':
          description: Login fail. Wrong password.
        '409':
          description: Email or username exist with error code (emai 0 or username 1)
          schema:
            type: integer
        '500':
          description: Internal Server Error
  /session/login:
    post:
      tags:
        - session
      summary: Login by email and password
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Email and password
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                format: email
                example: test@gmail.com
              password:
                type: string
                format: hash
                example: 127e6fbfe24a750e72930c220a8e138275656b8e5d8f48a98c3c92df2caba935
      responses:
        '200':
          description: Login success
          schema:
            $ref: '#/definitions/AUTH_RES'
        '400':
          description: Invalid parameter
        '401':
          description: Login fail. Wrong password.
        '404':
          description: Email not exist
        '500':
          description: Internal Server Error
  /session/logout:
    delete:
      tags:
        - session
      summary: Logout
      operationId: logout
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: sessionId
          required: true
      responses:
        '500':
          description: Internal Server Error
  /session/verify/email:
    get:
      tags:
        - session
      summary: Check Email exist
      operationId: checkEmailExist
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: email
          required: true
      responses:
        '200':
          description: Email exist
        '400':
          description: Invalid parameter
        '404':
          description: Email not exist
        '500':
          description: Internal Server Error
  /session/verify/username:
    get:
      tags:
        - session
      summary: Check username exist
      operationId: checkUsernameExist
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: username
          required: true
      responses:
        '200':
          description: username exist
        '400':
          description: Invalid parameter
        '404':
          description: username not exist
        '500':
          description: Internal Server Error
  /profile:
    get:
      tags:
        - profile
      summary: get profile by id
      operationId: profileById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: integer
          name: profileId
          required: true
      responses:
        '200':
          description: fetch profile success
          schema:
            $ref: '#/definitions/PROFILE_RES'
        '400':
          description: Invalid parameter
        '404':
          description: Profile not found
        '500':
          description: Internal Server Error
  /profile/me:
    get:
      tags:
        - profile
      summary: get my username
      operationId: profileMe
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: sessionId
          required: true
        - in: query
          type: integer
          name: profileId
          required: true
      responses:
        '200':
          description: fetch profile success
          schema:
            $ref: '#/definitions/PROFILE_RES'
        '400':
          description: Invalid parameter
        '401':
          description: sessionId unauthorized
        '500':
          description: Internal Server Error
  /media/image:
    post:
      tags:
        - media
      summary: Upload image and return url
      operationId: mediaImage
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: sessionId
          required: true
        - in: body
          name: FormData
          schema:
            type: object
            properties:
              file:
                type: object
      responses:
        '200':
          description: upload success
          schema:
            type: string
            format: string
            example: www.test.imagepath.jpg
        '400':
          description: Invalid parameter
        '401':
          description: sessionId unauthorized
        '500':
          description: Internal Server Error
  /project:
    post:
      tags:
        - project
      summary: create new project
      operationId: newProject
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: sessionId
          required: true
        - in: body
          name: FormData
          schema:
            $ref: '#/definitions/PROJECT_REQ'
      responses:
        '200':
          description: fetch profile success
          schema:
            $ref: '#/definitions/PROJECT_RES'
        '400':
          description: Invalid parameter
        '401':
          description: sessionId unauthorized
        '409':
          description: repeated project name
        '500':
          description: Internal Server Error
  /project/get:
    post:
      tags:
        - project
      summary: fetch project
      operationId: fetchProject
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: sessionId
          required: true
        - in: body
          name: FormData
          schema:
            $ref: '#/definitions/GetProjectReq'
      responses:
        '200':
          description: fetch profile success
          schema:
            type: array
            items:
              $ref: '#/definitions/PROJECT_RES'
        '400':
          description: Invalid parameter
        '401':
          description: sessionId unauthorized
        '500':
          description: Internal Server Error
  /project/detail:
    post:
      tags:
        - project
      summary: fetch project detail
      operationId: fetchProjectDetail
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: sessionId
          required: true
        - in: body
          name: FormData
          schema:
            $ref: '#/definitions/ProjectDetailReq'
      responses:
        '200':
          description: fetch profile success
          schema:
            type: array
            items:
              $ref: '#/definitions/ProjectDetailRes'
        '400':
          description: Invalid parameter
        '401':
          description: sessionId unauthorized
        '404':
          description: not found / permission denied
        '500':
          description: Internal Server Error
  /issue:
    post:
      tags:
        - issue
      summary: New issue
      operationId: newIssue
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: sessionId
          required: true
        - in: body
          name: FormData
          schema:
            $ref: '#/definitions/NewIssueReq'
      responses:
        '200':
          description: fetch profile success
          schema:
            type: array
            items:
              $ref: '#/definitions/NewIssueRes'
        '400':
          description: Invalid parameter
        '401':
          description: sessionId unauthorized
        '500':
          description: Internal Server Error
  /issue/project:
    post:
      tags:
        - issue
      summary: Get issue by project Id
      operationId: projectIssue
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: sessionId
          required: true
        - in: body
          name: FormData
          schema:
            $ref: '#/definitions/NewIssueReq'
      responses:
        '200':
          description: fetch profile success
          schema:
            type: array
            items:
              $ref: '#/definitions/NewIssueRes'
        '400':
          description: Invalid parameter
        '401':
          description: sessionId unauthorized
        '500':
          description: Internal Server Error
  /issue/get:
    post:
      tags:
        - issue
      summary: fetch issue
      operationId: getUserIssue
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: sessionId
          required: true
        - in: body
          name: FormData
          schema:
            $ref: '#/definitions/GetProjectReq'
      responses:
        '200':
          description: fetch profile success
          schema:
            type: array
            items:
              $ref: '#/definitions/NewIssueRes'
        '400':
          description: Invalid parameter
        '401':
          description: sessionId unauthorized
        '500':
          description: Internal Server Error
definitions:
  AUTH_RES:
    type: object
    required:
      - userId
      - username
      - sessionID
    properties:
      userId:
        type: integer
        format: integer
        example: 1
      username:
        type: string
        example: ting
      sessionID:
        type: string
        format: hash
        example: 82a9dda829eb7f8ffe9fbe49e45d47d2dad9664fbb7adf72492e3c81ebd3e29134d9bc12212bf83c6840f10e8246b9db54a4859b7ccd0123d86e5872c1e5082f
  PROFILE_RES:
    type: object
    required:
      - username
    properties:
      username:
        type: string
        example: ting
  PROFILE_RES2:
    type: object
    required:
      - username
      - photoUrl
    properties:
      username:
        type: string
        example: ting
      photoUrl:
        type: string
        example: www.image.jpg
  PROJECT_REQ:
    type: object
    required:
      - name
      - isPrivate
    properties:
      name:
        type: string
        example: ting's project
      description:
        type: string
        example: hello world
      isPrivate:
        type: boolean
        example: true
  GetProjectReq:
    type: object
    required:
      - user_id
      - timestamp
      - limit
      - isOwner
    properties:
      user_id:
        type: integer
        example: 15
      timestamp:
        type: string
        example: '2019-12-05T06:40:43.746+0000'
      limit:
        type: integer
        example: 15
      isOwner:
        type: boolean
        example: true
  PROJECT_RES:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: ting's project
      description:
        type: string
        example: hello world
      isPrivate:
        type: boolean
        example: true
      create_time:
        type: string
        example: '2019-12-05T06:40:43.746+0000'
      owner:
        type: string
        example: ting
  ProjectDetailReq:
    type: object
    required:
      - user
      - project
    properties:
      user:
        type: string
        example: test
      project:
        type: string
        example: test
  ProjectDetailRes:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: ting's project
      description:
        type: string
        example: hello world
      isPrivate:
        type: boolean
        example: true
      create_time:
        type: string
        example: '2019-12-05T06:40:43.746+0000'
      owner:
        type: string
        example: ting
      issue_count:
        type: integ
      finish_issue_count:
        type: integer
        example: 1
      member_count:
        type: integer
        example: 1
      tag_count:
        type: integer
        example: 1
  NewIssueReq:
    type: object
    properties:
      name:
        type: string
        example: new issue
      description:
        type: string
        example: hello world
      projectId:
        type: integer
        example: 1
      state:
        type: integer
        example: 1
      severity:
        type: integer
        example: 1
      priority:
        type: integer
        example: 1
      isReproducible:
        type: boolean
        example: true
  NewIssueRes:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: new issue
      description:
        type: string
        example: hello world
      projectId:
        type: integer
        example: 1
      state:
        type: integer
        example: 1
      severity:
        type: integer
        example: 1
      priority:
        type: integer
        example: 1
      isReproducible:
        type: boolean
        example: true
      create_time:
        type: string
        example: '2019-12-05T06:40:43.746+0000'
      ReportUser:
        type: string
        example: test
  GetProjectIssueReq:
    type: object
    properties:
      projectId:
        type: integer
        example: 2
      timestamp:
        type: string
        example: '2019-12-05T06:40:43.746+0000'
      limit:
        type: integer
        example: 1
